# Nom du projet 
name: 'SororIT'
version: '1.0.0'

# Indique le profil dbt à utiliser pour ce projet (doit correspondre au nom dans profiles.yml)
profile: 'SororIT'

# Chemins vers les différents types de fichiers utilisés par dbt
model-paths: ["models"]         # Modèles dbt
analysis-paths: ["analyses"]    # Analyses SQL
test-paths: ["tests"]            # Tests personnalisés
seed-paths: ["seeds"]            # Données brutes (CSV)
macro-paths: ["macros"]          # Macros Jinja personnalisées
snapshot-paths: ["snapshots"]    # Snapshots (suivi d'historique)

# Dossiers à nettoyer avec la commande `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuration des modèles
# Documentation complète : https://docs.getdbt.com/fr/docs/configuring-models

models:
  SororIT:
    +materialized: view

